### PR TITLE
Extra detail about configuring build path

### PR DESCRIPTION
**Pull request by ian-burnett**

### CODE REVIEW

**Comment by PhilWakelin** [comment]
Looks good but there is still the issue that there are no instructions or reference in the main readme about how to import the files into Eclipse and this is a precursor for deployment. Currently you have to go to the projects readme to get this information and I think this was the root of this issue.

**Comment by ian-burnett** [comment]
OK - I'll have a think.

**Comment by ian-burnett** [comment]
Added a short section at the top-level README to reference the instructions included in the `projects/` directory.

Any suggestions or comments @PhilWakelin ?

**Review by PhilWakelin — APPROVED** [review]
Finally approved.

**Pull request merged**
